const data = [
    {
      head: require("../../../Assets/airgaragelogo.png"),
      name1: "Gray Reyes",
      name2: "6cr",
      name3: "1",
      para: "One theory of passive investing is that every public company is the same, so there’s no",
      subheading: "Airgarage",
      service: "Service",
    },
    {
      head: require("../../../Assets/Airtable_Logo.png"),
      name1: "john Doe",
      name2: "3cr",
      name3: "6",
      para: "One theory of passive investing is that every public company is the same, so there’s no",
      subheading: "Airtable",
      service: "Product",
    },
    {
      head: require("../../../Assets/dave-logo.png"),
      name1: "Ionis Denis",
      name2: "4cr",
      name3: "2",
      para: "One theory of passive investing is that every public company is the same, so there’s no",
      subheading: "Dave",
      service: "Product",
    },
    {
      head: require("../../../Assets/Brightline.png"),
      name1: "Sydney Porter",
      name2: "3cr",
      name3: "1",
      para: "One theory of passive investing is that every public company is the same, so there’s no",
      subheading: "Brightline",
      service: "Ed tech",
    },
    {
      head: require("../../../Assets/clickup.png"),
      name1: "Neil Guzman",
      name2: "80Lks",
      name3: "2",
      para: "One theory of passive investing is that every public company is the same, so there’s no",
      subheading: "ClickUp",
      service: "Fintech",
    },
    {
      head: require("../../../Assets/bloomscope.png"),
      name1: "Lovis Hunter",
      name2: "60Lks",
      name3: "5",
      para: "One theory of passive investing is that every public company is the same, so there’s no",
      subheading: "Bloomscape",
      service: "Agritech",
    },
    {
      head: require("../../../Assets/Loom.png"),
      name1: "Donsnider",
      name2: "1cr",
      name3: "1",
      para: "One theory of passive investing is that every public company is the same, so there’s no",
      subheading: "Loom",
      service: "Healthcare",
    },
    {
      head: require("../../../Assets/Checkr_Logo.png"),
      name1: "Maisie Howie",
      name2: "40Lks",
      name3: "2",
      para: "One theory of passive investing is that every public company is the same, so there’s no",
      subheading: "Checkr",
      service: "Agritech",
    },
    {
      head: require("../../../Assets/codecov.png"),
      name1: "Mabel Mallen",
      name2: "3cr",
      name3: "3",
      para: "One theory of passive investing is that every public company is the same, so there’s no",
      subheading: "Codecov",
      service: "Product",
    },
    {
      head: require("../../../Assets/divvy.png"),
      name1: "Ted Newton",
      name2: "4cr",
      name3: "2",
      para: "One theory of passive investing is that every public company is the same, so there’s no",
      subheading: "Divvy",
      service: "Product",
    },
    {
      head: require("../../../Assets/enovy.png"),
      name1: "john Doe",
      name2: "2cr",
      name3: "3",
      para: "One theory of passive investing is that every public company is the same, so there’s no",
      subheading: "Envoy",
      service: "Agritech",
    },
    {
      head: require("../../../Assets/fabfitfun.png"),
      name1: "Cliff Tenny",
      name2: "90Lks",
      name3: "3",
      para: "One theory of passive investing is that every public company is the same, so there’s no",
      subheading: "Fabfitfun",
      service: "Service",
    },
  ];
  export default data;
  